### ISSUE TITLE
能不能再做出一个最常见的等待圆圈标志？

### ISSUE THREAD

**Issue by narutomst** [Mlearn/WaitBar_Matlab#1]
我的意思是waitcircle，就是几乎所有程序都会显示的那种一直在转的圈圈或者是动态花瓣。不需要知道具体进度，仅仅是让用户知道，程序正在执行请等待，在Matlab GUI里能不能实现？

**Comment by 777Arch** [comment]
这种应该做不了，据我所知 Matlab 本身不支持多线程操作，所以后台运算与 GUI 显示不能同步处理。
目前所有的 GUI 在做后台运算过程时界面都是卡死状态不能刷新的。
